Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -14,10 +14,36 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
+      - name: Check if macOSX.sdk exists
+        run: |
+          if [ -d "$(xcrun --sdk macosx --show-sdk-path)" ]; then
+            echo "✅ macOSX.sdk is available"
+          else
+            echo "❌ macOSX.sdk is missing"
+            exit 1
+          fi
+    
       - uses: maxim-lobanov/setup-xcode@v1
         with:
           xcode-version: ${{ matrix.xcode }}
-      - name: Debug info
+
+      - name: Show Xcodebuild version
+        run: xcodebuild -version
+
+      - name: Check if macOSX.sdk for selected Xcode ${{ matrix.xcode }} exists
         run: |
-            xcodebuild -version
-            xcrun --show-sdk-version
+          if [ -d "$(xcrun --sdk macosx --show-sdk-path)" ]; then
+            echo "✅ macOSX.sdk is available"
+          else
+            echo "❌ macOSX.sdk is missing"
+            exit 1
+          fi
+
+      - name: List available SDKs
+        run: xcodebuild -showsdks
+
+      - name: List selected SDK
+        run: xcrun --show-sdk-version
+
+      - name: List installed simulators & runtimes
+        run: xcrun simctl list
